- name: SonarQube Setup Playbook
  hosts: localhost
  gather_facts: true
  become: true
  vars_files:
    - /home/ubuntu/sonarqube-ansible/roles/sonarqube_setup/vars/main.yml
  roles:
    - sonarqube_setup
  handlers:
    - import_tasks: /home/ubuntu/sonarqube-ansible/roles/sonarqube_setup/handlers/main.yml

